### ISSUE TITLE
Custom Object Detection

### ISSUE THREAD

**Issue by chasemaier** [ModelDepot/tfjs-yolo-tiny#1]
Hi. Looks like an interesting start to a project here -- interested to see where to goes / take a look at the demo once that is released.

In the meantime, I'm curious if you had any insight on:

- The limitation you mention in the README about only supporting the Tiny flavor. Is that only a limitation for real-time video because of the resources required? If object detection was on a single image at a time, would the full models be more capable or is there some syntax/format issue that makes it incompatible?
- I'm particularly interested in using something like this (pure browser JS) but to identify custom objects in images that wouldn't be included in the YOLO dataset. Is there a process that you could describe for how to get a custom-trained YOLO (Tiny YOLO) data set (with 2 classes of objects) into the correct input format to be loaded as a model in this script?

**Comment by MikeShi42** [comment]
Wow glad you found this repo so quickly! We aren't even live yet :P Hopefully the live browser demo will be hosted by tonight.

1. It's a limitation due to tf.js (due to [YAD2K](https://github.com/allanzelener/YAD2K/blob/master/yad2k.py#L229-L237)) not having "native" support for the [reorg layer](https://github.com/pjreddie/darknet/blob/master/cfg/yolov2.cfg#L219-L220). Perhaps there's a way to get around it in native TF without custom layers, or tfjs might eventually get around to support custom layers. I honestly didn't have a lot of time to research into it since I'm currently mainly focusing on getting the Tiny version to work well (and iron out bugs in post-process code). Perhaps [Darkflow](https://github.com/thtrieu/darkflow) might have found a native TF way to do it? If you do find a solution, PRs are certainly welcome! 

2. Yes it should be possible. I'd look at YAD2K, specifically [this issue](https://github.com/allanzelener/YAD2K/issues/24#issuecomment-315803411) might be a good start. You can also of course train it using [Darknet](https://pjreddie.com/darknet/yolo/#train-coco) and port it over. I haven't tested this script for a non-coco trained model and most likely there will have to be modifications made, probably only in the [class index to class mapping](https://github.com/ModelDepot/tfjs-yolo-tiny/blob/master/src/index.js#L77). All other post-processing code should be agnostic to the number of classes, but again I haven't tested.

**Comment by MikeShi42** [comment]
In case you haven’t seen, the demo is out :) Link is on the readme!

Let me know if you run into any issues

**Comment by tngan** [comment]
@MikeShi42 Do you have an example on applying custom model?
